export const EVENT_CREATE_REQUEST = "EVENT_CREATE_REQUEST"
export const EVENT_CREATE_SUCCESS = "EVENT_CREATE_SUCCESS"
export const EVENT_CREATE_FAIL = "EVENT_CREATE_FAIL"

export const EVENT_GET_REQUEST = "EVENT_GET_REQUEST"
export const EVENT_GET_SUCCESS = "EVENT_GET_SUCCESS"
export const EVENT_GET_FAIL = "EVENT_GET_FAIL"

export const EVENTS_GET_REQUEST = "EVENTS_GET_REQUEST"
export const EVENTS_GET_SUCCESS = "EVENTS_GET_SUCCESS"
export const EVENTS_GET_FAIL = "EVENTS_GET_FAIL"

export const EVENT_UPDATE_REQUEST = "EVENT_UPDATE_REQUEST"
export const EVENT_UPDATE_SUCCESS = "EVENT_UPDATE_SUCCESS"
export const EVENT_UPDATE_FAIL = "EVENT_UPDATE_FAIL"

export const EVENT_DELETE_REQUEST = "EVENT_DELETE_REQUEST"
export const EVENT_DELETE_SUCCESS = "EVENT_DELETE_SUCCESS"
export const EVENT_DELETE_FAIL = "EVENT_DELETE_FAIL"