// @@CREATE
export const EVENT_CREATE_REQUEST = "EVENT_CREATE_REQUEST"
export const EVENT_CREATE_SUCCESS = "EVENT_CREATE_SUCCESS"
export const EVENT_CREATE_FAIL = "EVENT_CREATE_FAIL"

// @@READ
// BY ID
export const EVENT_GET_REQUEST = "EVENT_GET_REQUEST"
export const EVENT_GET_SUCCESS = "EVENT_GET_SUCCESS"
export const EVENT_GET_FAIL = "EVENT_GET_FAIL"
    // LIST
export const EVENTS_GET_REQUEST = "EVENTS_GET_REQUEST"
export const EVENTS_GET_SUCCESS = "EVENTS_GET_SUCCESS"
export const EVENTS_GET_FAIL = "EVENTS_GET_FAIL"

// @@UPDATE
export const EVENT_UPDATE_REQUEST = "EVENT_UPDATE_REQUEST"
export const EVENT_UPDATE_SUCCESS = "EVENT_UPDATE_SUCCESS"
export const EVENT_UPDATE_FAIL = "EVENT_UPDATE_FAIL"

// @@DELETE
// SOFT DELETE
export const EVENT_DELETE_REQUEST = "EVENT_DELETE_REQUEST"
export const EVENT_DELETE_SUCCESS = "EVENT_DELETE_SUCCESS"
export const EVENT_DELETE_FAIL = "EVENT_DELETE_FAIL"
    // HARD DELETE
export const EVENT_CLEAR_REQUEST = "EVENT_CLEAR_REQUEST"
export const EVENT_CLEAR_SUCCESS = "EVENT_CLEAR_SUCCESS"
export const EVENT_CLEAR_FAIL = "EVENT_CLEAR_FAIL"
    // RESET STATE
export const EVENT_CREATE_RESET = "EVENT_CREATE_RESET"
export const EVENT_GET_RESET = "EVENT_GET_RESET"
export const EVENTS_GET_RESET = "EVENTS_GET_RESET"
export const EVENT_UPDATE_RESET = "EVENT_UPDATE_RESET"
export const EVENT_DELETE_RESET = "EVENT_DELETE_RESET"
export const EVENT_CLEAR_RESET = "EVENT_CLEAR_RESET"