export const SUB_CATEGORY_LIST_REQUEST = 'SUB_CATEGORY_LIST_REQUEST'
export const SUB_CATEGORY_LIST_SUCCESS = 'SUB_CATEGORY_LIST_SUCCESS'
export const SUB_CATEGORY_LIST_FAIL = 'SUB_CATEGORY_LIST_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
